### ISSUE TITLE
node v10.x npm run dev报错

### ISSUE THREAD

**Issue by lokisama** [master-coder-ll/v2ray-manager-console#3]
系统环境：
$ cnpm -v
cnpm@6.1.1 
npm@6.14.2 
node@10.10.0
npminstall@3.27.0 
prefix=C:\Users\Administrator\AppData\Roaming\npm
win32 x64 10.0.10240
registry=https://r.npm.taobao.org

报错信息：
$ npm run dev

> vue-element-admin@4.2.1 dev F:\opt\v2ray-manager-console
> vue-cli-service serve

 INFO  Starting development server...
 10% building 2/2 modules 0 active ERROR  Error: Cannot find module 'core-js/modules/es6.regexp.constructor'
Error: Cannot find module 'core-js/modules/es6.regexp.constructor'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (F:\opt\v2ray-manager-console\mock\index.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (F:\opt\v2ray-manager-console\node_modules\_pirates@4.0.1@pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (F:\opt\v2ray-manager-console\node_modules\_pirates@4.0.1@pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at registerRoutes (F:\opt\v2ray-manager-console\mock\mock-server.js:10:30)
    at Object.module.exports.app [as after] (F:\opt\v2ray-manager-console\mock\mock-server.js:41:22)

处理办法：
package.json里修改为以下就过ok了
"dependencies": {
    ...
    "core-js": "^2.6.8",
    ...
}

**Comment by master-coder-ll** [comment]
我也不太懂前端。
