### ISSUE TITLE
这真能编译出来吗？

### ISSUE THREAD

**Issue by WeiMXi** [master-coder-ll/v2ray-manager-console#9]
nvm切换到16.9.1的nodejs，直接下载的[node_modules](https://gitee.com/wubie/vue2-element-admin-simplify/raw/master/%5Bbackup%5Dnode_modules.zip)丢到`git clone`下来的目录里，然后`npm run build:prod`错误不断
原先即使直接在`git clone`下来的目录里也会出现一样的依赖错误
开发者的依赖关系到底是怎么搞出来的？是不是没测试就丢上来了？

```text
[iyu@localhost v2ray-manager-console]$ nvm install 16.9.1
Downloading and installing node v16.9.1...
Downloading https://nodejs.org/dist/v16.9.1/node-v16.9.1-linux-x64.tar.xz...
################################################################################################################################################################################### 100.0%Computing checksum with sha256sum
Checksums matched!
Now using node v16.9.1 (npm v7.21.1)
Creating default alias: default -> 16.9.1 (-> v16.9.1)
[iyu@localhost v2ray-manager-console]$ nvm use 16.9.1
Now using node v16.9.1 (npm v7.21.1)
[iyu@localhost v2ray-manager-console]$ node -v
v16.9.1
[iyu@localhost v2ray-manager-console]$ npm run build:prod

> vue-element-admin@4.4.0 build:prod
> vue-cli-service build

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

⠙  Building for production...Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
⠸  Building for production...Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
⠏  Building for production...Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
⠋  Building for production...Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
⠧  Building for production...

 ERROR  Failed to compile with 4 errors                                                                                                                                         7:25:45 PM

These dependencies were not found:

* js-md5 in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/adminUser/components/UserDetail.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/login/index.vue?vue&type=script&lang=js& and 1 other
* vue-qr in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/account/userAccount.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save js-md5 vue-qr
 ERROR  Build failed with errors.
[iyu@localhost v2ray-manager-console]$ npm install --save js-md5 vue-qr
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.       
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN old lockfile raphael: No matching version found for raphael@2.2.0-c.
npm WARN old lockfile     at module.exports (/home/iyu/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /home/iyu/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/home/iyu/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:691:9)     
npm WARN old lockfile  Could not fetch metadata for raphael@2.2.0-c raphael: No matching version found for raphael@2.2.0-c.
npm WARN old lockfile     at module.exports (/home/iyu/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
npm WARN old lockfile     at /home/iyu/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
npm WARN old lockfile     at async Array.<anonymous> (/home/iyu/.nvm/versions/node/v16.9.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:691:9) {   
npm WARN old lockfile   code: 'ETARGET',
npm WARN old lockfile   type: 'version',
npm WARN old lockfile   wanted: '2.2.0-c',
npm WARN old lockfile   versions: [
npm WARN old lockfile     '1.4.7-14-gdbe241f',
npm WARN old lockfile     '1.4.7-npm-1.0.0',
npm WARN old lockfile     '1.4.7-npm-1.0.1',
npm WARN old lockfile     '2.1.0',
npm WARN old lockfile     '2.1.4',
npm WARN old lockfile     '2.2.0',
npm WARN old lockfile     '2.2.1',
npm WARN old lockfile     '2.2.3',
npm WARN old lockfile     '2.2.4',
npm WARN old lockfile     '2.2.6',
npm WARN old lockfile     '2.2.7',
npm WARN old lockfile     '2.2.8',
npm WARN old lockfile     '2.3.0'
npm WARN old lockfile   ],
npm WARN old lockfile   distTags: { latest: '2.3.0' },
npm WARN old lockfile   defaultTag: 'latest'
npm WARN old lockfile }
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vue-element-admin@4.4.0  
npm ERR! Found: eslint@6.7.2
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"6.7.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">=7.5.0" from @vue/cli-plugin-eslint@5.0.8
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"^5.0.8" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/iyu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iyu/.npm/_logs/2023-10-28T11_27_24_869Z-debug.log
[iyu@localhost v2ray-manager-console]$
```

**Comment by ayayime** [comment]
一样
